### ISSUE TITLE
runtime

### ISSUE THREAD

**Issue by zzm-hl** [aleksandrkim61/PolarMOT#2]
Could please provide the  runtime on KITTI?,I can not find it in paper.thank you!

**Comment by polarmot** [comment]
Hi, here is an excerpt from our rebuttal:
> Our GNN is capable of near-real-time inference: 33 FPS on NuScenes and 170 FPS on KITTI. 
KITTI is faster, because, by protocol, we only track objects visible in the forward-directed camera, which is a substantially lower number.

The code will include a script to run the tracker online and it will output more precise numbers on your hardware. The release will be done this week, so check in on Monday.
